#!/usr/bin/env node
'use strict';

// One-time (idempotent) assembly of a runnable MVDSV + ktx-lite sandbox under
// smoketest/sandbox/. Re-run with --force to re-download MVDSV and regenerate
// the rcon password. Safe to re-run any time; run.js always re-copies the
// freshly built qwprogs.dll before each scenario run regardless.

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const cfg = require('./lib/config');

const MVDSV_VERSION = '1.11';
const MVDSV_ASSET = 'mvdsv_windows_x64.exe';
const MVDSV_URL =
	`https://github.com/QW-Group/mvdsv/releases/download/${MVDSV_VERSION}/${MVDSV_ASSET}`;

const EXAMPLE_CONFIGS = path.join(cfg.REPO_ROOT, 'resources', 'example-configs');
const STEAM_ID1 = process.env.STEAM_ID1
	|| 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Quake\\id1';

const force = process.argv.includes('--force');

function log(msg) {
	console.log(`[setup] ${msg}`);
}

function download(url, destPath) {
	return new Promise((resolve, reject) => {
		const file = fs.createWriteStream(destPath);

		function get(u, redirectsLeft) {
			https.get(u, { headers: { 'User-Agent': 'ktx-lite-smoketest' } }, (res) => {
				if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
					if (redirectsLeft <= 0) {
						reject(new Error(`Too many redirects downloading ${url}`));
						return;
					}
					res.resume();
					get(res.headers.location, redirectsLeft - 1);
					return;
				}

				if (res.statusCode !== 200) {
					reject(new Error(`Download failed: HTTP ${res.statusCode} for ${u}`));
					return;
				}

				res.pipe(file);
				file.on('finish', () => file.close(() => resolve()));
			}).on('error', reject);
		}

		get(url, 5);
	});
}

async function ensureMvdsv() {
	if (fs.existsSync(cfg.MVDSV_EXE) && !force) {
		log('mvdsv.exe already present (use --force to re-download)');

		return;
	}

	log(`downloading MVDSV ${MVDSV_VERSION} (windows x64)...`);

	const tmp = `${cfg.MVDSV_EXE}.download`;

	await download(MVDSV_URL, tmp);
	fs.renameSync(tmp, cfg.MVDSV_EXE);
	log('mvdsv.exe downloaded');
}

function copyKtxTree() {
	log('copying ktx example config tree...');
	fs.cpSync(path.join(EXAMPLE_CONFIGS, 'ktx'), cfg.KTX_DIR, { recursive: true, force: true });
}

function copyMapEnts() {
	const srcDir = path.join(EXAMPLE_CONFIGS, 'id1', 'maps');
	const destDir = path.join(cfg.ID1_DIR, 'maps');

	fs.mkdirSync(destDir, { recursive: true });

	for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
		if (entry.isFile() && entry.name.endsWith('.ent')) {
			fs.copyFileSync(path.join(srcDir, entry.name), path.join(destDir, entry.name));
		}
	}

	log('copied map .ent files');
}

function copyPaks() {
	fs.mkdirSync(cfg.ID1_DIR, { recursive: true });

	for (const pak of ['PAK0.PAK', 'PAK1.PAK']) {
		const src = path.join(STEAM_ID1, pak);

		if (!fs.existsSync(src)) {
			throw new Error(
				`Cannot find ${pak} at ${src}. Set the STEAM_ID1 env var to your Quake id1 `
				+ `folder, or copy PAK0.PAK/PAK1.PAK into smoketest/sandbox/id1/ manually.`);
		}

		fs.copyFileSync(src, path.join(cfg.ID1_DIR, pak));
	}

	log('copied PAK0.PAK + PAK1.PAK');
}

function copyBuiltDll() {
	const candidateDirs = fs.readdirSync(cfg.REPO_ROOT, { withFileTypes: true })
		.filter((e) => e.isDirectory() && /^build/i.test(e.name))
		.map((e) => path.join(cfg.REPO_ROOT, e.name));

	let best = null;

	for (const dir of candidateDirs) {
		for (const rel of ['qwprogs.dll', path.join('Release', 'qwprogs.dll')]) {
			const p = path.join(dir, rel);

			if (fs.existsSync(p)) {
				const mtimeMs = fs.statSync(p).mtimeMs;

				if (!best || mtimeMs > best.mtimeMs) {
					best = { path: p, mtimeMs };
				}
			}
		}
	}

	if (!best) {
		throw new Error(
			'No built qwprogs.dll found under ktx/build*/. Build the project first, e.g.:\n'
			+ '  cmake -S . -B build_msvc -G "Visual Studio 17 2022" -A x64\n'
			+ '  cmake --build build_msvc --config Release');
	}

	fs.copyFileSync(best.path, path.join(cfg.KTX_DIR, 'qwprogs.dll'));
	log(`copied ${path.relative(cfg.REPO_ROOT, best.path)} -> sandbox/ktx/qwprogs.dll`);
}

function ensureRconPassword() {
	if (fs.existsSync(cfg.RCON_PASSWORD_FILE) && !force) {
		return cfg.readRconPassword();
	}

	const pw = crypto.randomBytes(12).toString('hex');

	fs.writeFileSync(cfg.RCON_PASSWORD_FILE, pw);

	return pw;
}

function writeSmoketestCfg(rconPassword) {
	const text = '// generated by smoketest/setup.js -- do not edit by hand\n'
		+ 'sv_progtype 1\n'
		+ 'sv_progsname qwprogs\n'
		+ `rcon_password ${rconPassword}\n`
		+ 'maxclients 16\n'
		+ 'k_defmode ""\n'
		// The mod's one-shot bot-map-support probe runs exactly 20 engine
		// frames after process start (BotStartFrame() in bot_commands.c,
		// a static counter -- never re-armed, so this is a once-per-process
		// check, not once-per-map). It only sets map_supported if
		// `deathmatch` is already nonzero at that instant. Since deathmatch
		// otherwise only gets set later via the mod's own config-reset
		// cascade (game-logic-triggered, i.e. after frame 0), that races
		// frame 20 and often loses in a cold headless boot. Setting it here
		// applies at engine command-line parse time, before frame 1.
		+ 'deathmatch 1\n';

	fs.writeFileSync(path.join(cfg.KTX_DIR, cfg.SMOKETEST_CFG_NAME), text);
	log(`wrote sandbox/ktx/${cfg.SMOKETEST_CFG_NAME}`);
}

// The mod re-execs configs/reset.cfg -> server.cfg -> pwd.cfg/mvdsv.cfg
// whenever a client disconnects and zero *humans* remain connected
// (src/client.c ~line 2660, execute_rules_reset()). Since our sandbox never
// has a human client, that fires on every bot disconnect (e.g. our own
// map-change smoke test) and would silently reset rcon_password to ""
// (disabling rcon) and maxclients back to 8. Patch the copied config files
// themselves so a reset re-applies our values instead of stock ones.
function patchPersistentConfigs(rconPassword) {
	const pwdCfgPath = path.join(cfg.KTX_DIR, 'pwd.cfg');
	const pwdCfg = fs.readFileSync(pwdCfgPath, 'utf8')
		.replace(/^rcon_password\s+"[^"]*"/m, `rcon_password\t\t"${rconPassword}"`);

	fs.writeFileSync(pwdCfgPath, pwdCfg);

	const mvdsvCfgPath = path.join(cfg.KTX_DIR, 'mvdsv.cfg');
	const mvdsvCfg = fs.readFileSync(mvdsvCfgPath, 'utf8')
		.replace(/^maxclients\s+\d+/m, 'maxclients                    16')
		// The harness fires several rcon commands back-to-back per scenario
		// (setup lines, "mod addbot" per bot, status polling); the stock
		// limit of 3/sec is meant to slow down password brute-forcing over
		// the network, which doesn't apply to our own local automation.
		.replace(/^sv_rconlim\s+\d+/m, 'sv_rconlim                     50');

	fs.writeFileSync(mvdsvCfgPath, mvdsvCfg);

	log('patched pwd.cfg + mvdsv.cfg so resets keep the smoketest rcon password/maxclients/rconlim');
}

async function main() {
	fs.mkdirSync(cfg.SANDBOX_DIR, { recursive: true });

	await ensureMvdsv();
	copyKtxTree();
	copyMapEnts();
	copyPaks();
	copyBuiltDll();

	const pw = ensureRconPassword();

	writeSmoketestCfg(pw);
	patchPersistentConfigs(pw);

	log('sandbox ready.');
}

main().catch((err) => {
	console.error('[setup] FAILED:', err.message);
	process.exit(1);
});
